import type { Metadata } from "next";
import { absoluteUrl } from "@/lib/site-url";

/**
 * Shared Open Graph / Twitter preview image — generated by
 * src/app/opengraph-image.tsx (1200x630 PNG, served at /opengraph-image).
 */
export const ogImage = {
  url: absoluteUrl("/opengraph-image"),
  width: 1200,
  height: 630,
  alt: "भारत पहचान • BharatPahchan — डिजिटल अभियान, सुरक्षित पहचान",
};

type PageSeoInput = {
  /** Short page title; appends " | BharatPahchan" via the root layout template. */
  title: string;
  description: string;
  /** Page path used for the canonical URL and og:url (e.g. "/services"). */
  canonical: string;
  /** Optional shorter description for social cards. Falls back to `description`. */
  ogDescription?: string;
  /** Extra metadata to merge on top (used by special pages). */
  extra?: Metadata;
};

/**
 * Builds consistent per-page metadata (OpenGraph + Twitter image cards) so
 * every route shares the same branded preview image and social description.
 */
export function seo({
  title,
  description,
  canonical,
  ogDescription,
  extra,
}: PageSeoInput): Metadata {
  const socialTitle = `${title} | BharatPahchan`;
  const socialDescription = ogDescription ?? description;

  return {
    ...(extra ?? {}),
    title,
    description,
    alternates: { canonical },
    openGraph: {
      title: socialTitle,
      description: socialDescription,
      url: canonical,
      type: "website",
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title: socialTitle,
      description: socialDescription,
      images: [ogImage.url],
    },
  };
}
